# A Workshop Introduction to NumPy

The Python language is an excellent tool for general-purpose programming, with a highly readable syntax, rich and powerful data types (strings, lists, sets, dictionaries, arbitrary length integers, etc) and a very comprehensive standard library. It was not, however, designed specifically for mathematical and scientific computing. Neither the language nor its standard library have facilities for the efficient representation of multidimensional datasets, tools for linear algebra and general matrix manipulations (essential building blocks of virtually all scientific computing).

For example, Python lists are very flexible containers that can be nested arbitrarily deep and can hold any Python object in them, but they are poorly suited to represent common mathematical constructs like vectors and matrices. It is for this reason that NumPy exists.

## Workshop Objectives

The aims of this workshop are to enable you to:

  - manipulate numerical arrays
  - perform efficient array calculations

## Table of Contents

* [Getting Started with Numpy](#getting-started)
* [The Numpy Array](#array)
* [Motivation: what are arrays good for?](#motivation)
* [The Array Object](#array-object)
* [Application: Calculations -- Arithmetic and Broadcasting](#arithmetic_and_broadcasting)
* [Application: Calculations -- Statistics](#statistics)
* [Application: Efficiency](#efficiency)
* [Conclusions](#conclusions)

## Style
This workshop is a hands on coding workshop with discussion sections.  It can be treated as an exercise for an individual, but the intent is to work as a group with an instructor.

Topics are introduced, followed by worked examples and exploration suggestions.  These should be attempted individually or in small groups (making sure everyone is keeping their own notes).
Each topic concludes with a review and discussion session for the whole group.

The Jupyter notebook provides each participant with an environment to run code and make notes.  We recommend that you take your own copy of the workshop notebook and customise it through the workshop.
This should provide you with a useful resource to refer back to.

## Getting Started with NumPy <a class="anchor" id="getting-started"></a>
NumPy is the fundamental package for scientific computing with Python. Its primary purpose is to provide a powerful N-dimensional array object; the focus for this workshop.

To begin with let's import NumPy, check where it is being imported from and check the version.

In [1]:
# numpy is generally imported as 'np'
import numpy as np
print(np)
print(np.__version__)

<module 'numpy' from '/opt/scitools/environments/default/2017_02_21/lib/python2.7/site-packages/numpy/__init__.py'>
1.11.1


### Documentation
Here is a link to the NumPy documenetation for v1.11:
https://docs.scipy.org/doc/numpy-1.11.0/reference/

### Create an Array

There are many ways to create a numpy array, such as:

In [2]:
anarray = np.array((2, 3, 5, 7, 11, 13, 17, 19, 23))

### Experiment
Use the code cells below to experiment with array creation.

What can you find out about the arrays you have created?

## The NumPy Array <a class="anchor" id="array"></a>

## Motivation: what are arrays good for? <a class="anchor" id="motivation"></a>

### Fast Calculations

NumPy provides routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.

It is a lot faster than Python alone for numerical computing tasks.

Element-by-element operations are the “default mode” when an ndarray is involved, but the element-by-element operation is speedily executed by pre-compiled C code. 

### Clear Syntax

In NumPy

`c = a * b`

calculates the element-wise product of `a` and `b`, at near-C speeds, but with the code simplicity we expect from something based on Python.

This demonstrates a core feature of NumPy: 'vectorization'.  

Loops iterating through elements of arrays are not required, which can make code easier to read, as well as performing fast calculations.

### Calculation with Broadcasting

There are times when you need to perform calculations between NumPy arrays of different sizes.  For many cases, NumPy provides the means to achieve this effectively using 'broadcasting', where the shape of the input arrays differs, but the shape of the target array may be inferred, and is thus computed directly.

## The Array Object <a class="anchor" id="array-object"></a>

The multidimensional array object is the core of NumPy's power.  Let us explore this object some more.

### Array properties

Let's create a NumPy array and take a look at some of its properties.

In [2]:
arr = np.ones((3, 2, 4))

print("Array shape:", arr.shape)
print("Array element dtype:", arr.dtype)

('Array shape:', (3, 2, 4))
('Array element dtype:', dtype('float64'))


See if you can also find out the array's:

* number of dimensions,
* number of elements, and
* amount of memory used.

Hint: you can use `help(object)` to look up the documentation on any object.

Make some more arrays. Some different ways to create arrays can be found at https://docs.scipy.org/doc/numpy/user/basics.creation.html. What are the properties of your arrays?

What else can you find out about these arrays?

### Indexing

You can index NumPy arrays in the same way as any other Python iterables, by using square brackets `[]`. This means we can index to retrieve a single element, multiple consecutive elements, or a more complex sequence:

In [3]:
arr = np.array([1, 2, 3, 4, 5, 6])
print "arr --", arr
print "arr[2] --", arr[2]
print "arr[2:5] --", arr[2:5]
print "arr[::2] --", arr[::2]

arr -- [1 2 3 4 5 6]
arr[2] -- 3
arr[2:5] -- [3 4 5]
arr[::2] -- [1 3 5]


You can also index multidimensional arrays in a logical way using an enhanced indexing syntax. Remember that Python uses zero-based indexing!

In [4]:
lst_2d = [[1, 2, 3], [4, 5, 6]]
arr_2d = np.array(lst_2d)

print "2D list:"
print lst_2d
print
print "2D array:"
print arr_2d
print
print "Single array element:"
print arr_2d[1, 2]

2D list:
[[1, 2, 3], [4, 5, 6]]

2D array:
[[1 2 3]
 [4 5 6]]

Single array element:
6


#### Exercise #//n/

##### Part 1

Why do these indexing examples give the stated results?

 * result of `arr_2d[1, 0]` is `4`
 * result of `arr_2d[0]` is `[1, 2, 3]`
 * result of `arr_2d[1, 1:]` is `[5, 6]`
 * result of `arr_2d[0, ::2]` is `[[1, 3], [4, 6]]`

##### Part 2

How would you index `arr_2d` to retrieve:

 * the third value (`3`),
 * the second row (`[4, 5, 6]`), 
 * the first column (`[1, 4]`), and
 * the first column, retaining the outside dimension (`[[1, 4]]`)?

### Arrays are not lists

Question: why do the following examples produce different results?

In [5]:
print lst_2d[0:2][1]
print arr_2d[0:2, 1]

[4, 5, 6]
[2 5]


The result we just received points to an important piece of learning, which is that in most cases NumPy arrays behave very differently to Python lists. Let's explore the differences (and some similarities) between the two.

TODO:
 * dtype : homogeneous : promotion

**Expected duration:** ~ 20 mins

#### The Array Object: Summary of key  points
 * properties : `shape`, `dtype`
 * creation : `array([list])`, `ones`, `zeros`, `arange`, `linspace`
 * indexing like Python objects : integers and slices
 * indexing produces further array objects
 * multi-dimensional indexing with multiple indices
 * indexing differences from list-of-lists


## Application: Calculations <a class="anchor" id="app-calc"></a>

### Elementwise Arithmetic <a class="anchor" id="arithmetic_and_broadcasting"></a>

You can use NumPy to perform arithmetic operations between two arrays in an element-by-element fashion.

In [6]:
arr1 = np.arange(4)
arr2 = np.arange(4)

print arr1, '+', arr2, '=', arr1 + arr2

[0 1 2 3] + [0 1 2 3] = [0 2 4 6]


#### Exercise #//n/

Define some arrays and compute some results for different operators. Put the operations in different cells and see what works and what doesn't.

It makes intrinsic sense that you should be able to add a constant to all values in an array:

In [7]:
arr = np.arange(4)
const = 5

print "Original array:", arr
print
print "Array + const:", arr + const

Original array: [0 1 2 3]

Array + const: [5 6 7 8]


### Broadcasting

There are times when you need to perform calculations between NumPy arrays of different sizes.

For example, suppose you have maximum temperatures from each of three recording stations, recorded on two separate days.

In [8]:
daily_records = np.array([[12, 14, 16], [11, 13, 15]])
print
print 'raw data:'
print daily_records


raw data:
[[12 14 16]
 [11 13 15]]


Each station is known to overstate the maximum recorded temperature by a different known constant value. You wish to subtract the appropriate offset from each station's values.

You can do that like this:

In [9]:
offset = np.array([2, 1, 4])

corrected_records = daily_records - offset
print
print 'corrected values:'
print corrected_records


corrected values:
[[10 13 12]
 [ 9 12 11]]


NumPy allows you to do this easily using a powerful piece of functionality called **broadcasting**.

Broadcasting is a way of treating the arrays ***as if*** they had the same dimensions, and thus have elements all corresponding.  It is then easy to perform the calculation, element-wise.  
It does this by matching dimensions in one array to the other where possible, and using repeated values where there is no corresponding dimension in the other array.

#### Rules of Broadcasting

Broadcasting applies these three rules:

1.    If the two arrays differ in their number of dimensions, the shape of the array with fewer dimensions is padded with ones on its leading (left) side.

1.    If the shape of the two arrays does not match in any dimension, either array with shape equal to 1 in a given dimension is stretched to match the other shape.

1.    If in any dimension the sizes disagree and neither has shape equal to 1, an error is raised.

Note that all of this happens without ever actually creating the expanded arrays in memory! This broadcasting behavior is in practice enormously powerful, especially given that when NumPy broadcasts to create new dimensions or to 'stretch' existing ones, it doesn't actually duplicate the data. In the example above the operation is carried out as if the scalar 1.5 was a 1D array with 1.5 in all of its entries, but no actual array is ever created. This can save lots of memory in cases when the arrays in question are large. As such this can have significant performance implications.

![Illustration of broadcasting](../images/fig_broadcast_visual_1.png)

([image source](http://www.astroml.org/book_figures/appendix/fig_broadcast_visual.html))

#### Exercise #//n/
 1. Run some extra exercises
 1. Allow a space for play with delegates' own examples - and hopefully they will hit a problem that needs to be broadcast.

#### Reshaping arrays to aid broadcasting

NumPy allows you to change the shape of an array, so long as the total number of elements in the array does not change.

For example, we could reshape a flat array with 12 elements to a 2D array with shape `(2, 6)`, or `(3, 2, 2)`, or even `(3, 4, 1)`. 

We could not, however, reshape it to have shape `(2, 5)`, because the total number of elements would not be kept constant.

Now suppose you want to apply a correction for each day.
For example, you might try :

```python
days_adjust = np.array([1.5, 3.7])
adjusted = daily_records - days_adjust
```
but that results in :
```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-8-158daf2f21f2> in <module>()
      1 days_adjust = np.array([1.5, 3.7])
----> 2 adjusted = daily_records - days_adjust
      3 print adjusted

ValueError: operands could not be broadcast together with shapes (2,3) (2,) 
```

Clearly, this doesn't work !

#### Exercise #//n/

With reference to the above rules of broadcasting:
 1. describe why the above attempt to subtract `days_adjust` fails
 1. work out how you can modify the 'days_adjust' array to get the desired result.  
    Hint: imagine how the 'days_adjust' values *should* look, when expanded to match the dimensions of 'daily_records'.

#### Exercise #//n+1/
Sometimes an operation will produce a result, but not the one you wanted.

For example, suppose we have :
```python
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])
```

and we wish to add 0, 100 and 400 ***to the rows***.
That is,

```python
B = np.array([0, 100, 400])
# and...
desired_result = np.array([[  1,   2,   3],
                           [104, 105, 406],
                           [407, 407, 409]])
```

##### Questions:
 1. what will be the result of simply adding A and B ?
 1. how can you perform the correct calculation on A and B to get `desired_result` ?

Let's return to the daily maximum temperature example. Imagine that one day you receive four days' worth of maximum temperature values for the three sites, but for some reason the data are malformed into one long list of values. Nevertheless, you still need to apply the correct offsets to each site's values.

You can assume that the ordering of the values is the same as in the earlier example. That is, the order is `[day1-station1, day1-station2, day1-station3, day2-station1, ...]` and so on.

    four_days = [16, 14, 12, 15, 14, 14, 16, 11, 9, 13, 12, 10]

##### Questions:

 1. Suppose you want to remove the daily offsets, as before: Use broadcasting and reshape to achieve this.
 2. Suppose the values were supplied in a different order, with adjacent days for each station, i.e. `[day1-station1, day2-station1, day3-station1, day1-station2, day2-station2, day3-station2, ...]`.  Write code to handle this data.

Now go and play! (How do we structure this?)

You could review some of your experiments that failed from the earlier "Elementwise Arithmetic" section and see if you can now make them work.

#### Broadcasting: Summary of key  points

 * operations can be performed between arrays of different shapes
 * the arrays' dimensions are aligned according to fixed rules; where one input lacks a given dimension, values are repeated.
 * reshaping can be used to get arrays to combine as required.

### Statistics <a class="anchor" id="statistics"></a>

Numpy arrays support many common statistical calculations. For a list of common operations, see : https://docs.scipy.org/doc/numpy/reference/routines.statistics.html.

_It feels like we could do with some more written/spoken discussion here..._

#### Exercise nn.mm
 * What is the mean value over all the values in our `daily_records` array, given by the `np.mean()` function ?
 * What other similar statistical operations exist (see above link) ?
 * A mean value can also be calculated with `<array>.mean()`.  Is that the same thing ?
 * How should you calculate a median value -- with `np.median(array)` or `array.median()` ?

Used without any further arguments, statistical functions simply reduce the whole array to a single value.  In practice, however, we very often want to calculate statistics over only *some* of the dimensions.

For example, given the above `daily_records` data, we might want :

* (a) an average over all days, for each station, or
* (b) an average over all stations, for each day.

#### Exercise nn.mm

* produce the two kinds of single-axis average mentioned above -- that is, 
  * (a) over all days at each station, 
  * (b) over all stations for each day.
  * (Hint: look at the documentation -- the term 'axis' in NumPy refers to the number of a dimension.)
* Create a sample 3-D array, to represent air temperature at given times, X and Y positions :
   1. how can you form a mean over all X and Y at each timestep ?  
   1. what shape does such result have ?
   1. how can you calculate the `np.ptp` statistic of this data in a similar form, i.e. for all X and Y at each timestep ?  
     N.B. `ptp` means a peak-to-peak range, i.e. "max(data) - min(data)".

#### Statistics : Summary of key points
 * most statistical functions are available in two different forms, as in `array.mean()` and also `np.mean(array)`,
   the choice being mostly a question of style.
 * statistical operations operate over, and remove (or "collapse") the array dimensions that they are applied to.
 * an "axis" keyword specifies operation over dimensions : this can be one; multiple; or all.
   Note: not all operations permit operation over specifically selected dimensions
 * Statistical operations are not really part of Numpy itself, but are defined by the higher-level Scipy project.


### Masked Arrays

Real-world measurements processes often result in certain datapoint values being uncertain or completely absent.  This is usually indicated by additional data quality information, stored alongside the data values.

For example, we might know that in our previous `daily_records` data, the value for station-2 on day-1 is invalid.

data = np.array(

In these cases we need to calculate statistics that include only ***valid*** datapoints.  Numpy provides a "masked array" type for this type of calculation.

To represent the above-mentioned missing datapoint, we can make a masked version of the data :

In [10]:
daily_records = np.array([[12, 14, 16], [11, 13, 15]])
masked_data = np.ma.masked_array(daily_records)
masked_data[0, 1] = np.ma.masked
print 'unmasked average = ', np.mean(daily_records)
print 'masked average = ', np.ma.mean(masked_data)


unmasked average =  13.5
masked average =  13.4


# Efficiency <a class="anchor" id="efficiency"></a>

## Loops and Vectorised Operations

We will now explore calculation performance and consider efficiency in terms of processing time.

Firstly let's look at a simple processing time tool that is provided in notebooks; ``%%timeit`` :

In [11]:
%%timeit 
x = range(500)

100000 loops, best of 3: 5.02 µs per loop


Repeat that, specifying only 100 loops and fastest time of 5 runs

In [12]:
%%timeit -n 100 -r 5
x = range(500)

100 loops, best of 5: 5.07 µs per loop


This gives us an easy way to evaluate performance for implementations ...

In [13]:
rands = np.random.random(1000000).reshape(100, 100, 100)

In [14]:
%%timeit -n 10 -r 5
overPointEightLoop = 0
for i in range(100):
    for j in range(100):
        for k in range(100):
            if rands[i, j, k] > 0.8:
                overPointEightLoop +=1

10 loops, best of 5: 415 ms per loop


In [15]:
%%timeit -n 10 -r 5
overPointEightWhere = rands[rands > 0.8].size

10 loops, best of 5: 9.24 ms per loop


## Views on Arrays
NumPy attempts to not make copies of arrays unless it is explicitly told to.  

Many NumPy operations will produce a reference to an existing array, known as a "view", instead of making a whole new array.

For example: Indexing and reshaping provide a view of the same memory wherever possible.

In [16]:
arr = np.arange(8)
arr_view = arr.reshape(2, 4)

# Print the "view" array from reshape.
print 'Before\n', arr_view

# Update the first element of the original array.
arr[0] = 1000

# Print the "view" array from reshape again,
# noticing the first value has changed.
print 'After\n', arr_view

Before
[[0 1 2 3]
 [4 5 6 7]]
After
[[1000    1    2    3]
 [   4    5    6    7]]


What this means is that if one array (`arr`) is modified, the other (`arr_view`) will also be updated :  the same memory is being shared.

This is a valuable tool which enables the system memory overhead to be managed, which is particularly useful when handling lots of large arrays. 
The lack of copying allows for very efficient vectorized operations.

Remember, this behaviour is automatic in most of NumPy, so it requires some consideration in your code, it can lead to some bugs that are hard to track down.
For example, if you are changing some elements of an array that you are using elsewhere, you may want to explicitly copy that array before making changes.

If in doubt, you can always copy the data to a different block of memory with the `copy()` method.

For example ...

In [17]:
arr = np.arange(8)
arr_view = arr.reshape(2, 4).copy()

# Print the "view" array from reshape.
print 'Before\n', arr_view

# Update the first element of the original array.
arr[0] = 1000

# Print the "view" array from reshape again,
# noticing the first value has changed.
print 'After\n', arr_view

Before
[[0 1 2 3]
 [4 5 6 7]]
After
[[0 1 2 3]
 [4 5 6 7]]


# Conclusions <a class="anchor" id="conclusions"></a>

# Further Reading <a class="anchor" id="further"></a>

A quick list of some topics and facilities you probably ought to know about, but we did not have time for

**TODO:** add clickable links to documentation to all these

Concepts:
  *  module functions and array methods
  *  masked arrays and missing data
    * ".mask", ".data", ".fill_value", ".filled()"
    * NaNs and nan-functions ('nanmean', 'nanmax' etc)
    * boolean array indexing
  *  matrix multiply
  *  C and Fortran storage order
  *  file i/o

Terminology:
  *  ufunc
  *  boolean array
  *  "fancy" indexing

Concrete functions
  *  empty
  *  meshgrid
  *  stack  + concatenate
  *  transpose, ".T"
